// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrkxovunejlbqphxqnuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZya3hvdnVuZWpsYnFwaHhxbnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NTAxNzQsImV4cCI6MjA1NTAyNjE3NH0.lZxebcdjnUKDy2RG16Qd0aZgr7tQO9ONaQzQ_cVuPeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);